#!/usr/bin/env bash
#
# -- constant variables

#
function init() {
    print_step "init()"
    if [ -f "$(pwd)/terminal-colors.conf" ]; then
    source "$(pwd)/terminal-colors.conf"
    else
        echo -e "-- (!) ERROR: No file with color codes in current directory. --"
        echo -e "-- check current directory (terminal-colors.conf). --"
        ls -lah
        echo -e "---- TERMINATE ----"
        exit 1
    fi
    # source "./TerminalColorCodes.sh"
    # /mnt/hdd3/AL/0W/My_OS_Install_Script/os_install/ArchLinux_script/tests/colors/TerminalColorCodes.sh
    if [ -f "$(pwd)/messages.sh" ]; then
    source "$(pwd)/messages.sh"
    else
        echo -e "-- (!) ERROR: No file with color codes in current directory. --"
        echo -e "-- check current directory (messages.sh). --"
        ls -lah
        echo -e "---- TERMINATE ----"
        exit 1
    fi
    # source "./TerminalColorCodes.sh"
    # /mnt/hdd3/AL/0W/My_OS_Install_Script/os_install/ArchLinux_script/tests/colors/TerminalColorCodes.sh
}
#
function execute_step() {
    local STEP="$1"
    eval "$STEP"
}
#
function print_step() {
    STEP="$1"
    echo -e "${UBYellow}-- ${STEP} step --${Color_Off}"
}
#
function regular() {
    print_step "regular()"
    echo -e "-- -- -- --"
    echo -e "${Black}${MSG1}${Color_Off}"
    echo -e "${Black}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${Red}${MSG1}${Color_Off}"
    echo -e "${Red}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${Green}${MSG1}${Color_Off}"
    echo -e "${Green}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${Yellow}${MSG1}${Color_Off}"
    echo -e "${Yellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${Blue}${MSG1}${Color_Off}"
    echo -e "${Blue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${Purple}${MSG1}${Color_Off}"
    echo -e "${Purple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${Cyan}${MSG1}${Color_Off}"
    echo -e "${Cyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${White}${MSG1}${Color_Off}"
    echo -e "${White}${MSG2}${Color_Off}"
    echo -e ""
}
#
function bold() {
    print_step "bold()"
    echo -e "-- -- -- --"
    echo -e "${BBlack}${MSG1}${Color_Off}"
    echo -e "${BBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BRed}${MSG1}${Color_Off}"
    echo -e "${BRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BGreen}${MSG1}${Color_Off}"
    echo -e "${BGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BYellow}${MSG1}${Color_Off}"
    echo -e "${BYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BBlue}${MSG1}${Color_Off}"
    echo -e "${BBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BPurple}${MSG1}${Color_Off}"
    echo -e "${BPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BCyan}${MSG1}${Color_Off}"
    echo -e "${BCyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BWhite}${MSG1}${Color_Off}"
    echo -e "${BWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function underline() {
    print_step "underline()"
    echo -e "-- -- -- --"
    echo -e "${UBlack}${MSG1}${Color_Off}"
    echo -e "${UBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${URed}${MSG1}${Color_Off}"
    echo -e "${URed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UGreen}${MSG1}${Color_Off}"
    echo -e "${UGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UYellow}${MSG1}${Color_Off}"
    echo -e "${UYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBlue}${MSG1}${Color_Off}"
    echo -e "${UBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UPurple}${MSG1}${Color_Off}"
    echo -e "${UPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UCyan}${MSG1}${Color_Off}"
    echo -e "${UCyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UWhite}${MSG1}${Color_Off}"
    echo -e "${UWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function bold_underline() {
    print_step "bold_underline()"
    echo -e "-- -- -- --"
    echo -e "${UBBlack}${MSG1}${Color_Off}"
    echo -e "${UBBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBRed}${MSG1}${Color_Off}"
    echo -e "${UBRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBGreen}${MSG1}${Color_Off}"
    echo -e "${UBGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBYellow}${MSG1}${Color_Off}"
    echo -e "${UBYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBBlue}${MSG1}${Color_Off}"
    echo -e "${UBBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBPurple}${MSG1}${Color_Off}"
    echo -e "${UBPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBCyan}${MSG1}${Color_Off}"
    echo -e "${UBCyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBWhite}${MSG1}${Color_Off}"
    echo -e "${UBWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function background() {
    print_step "background()"
    echo -e "-- -- -- --"
    echo -e "${On_Black}${MSG1}${Color_Off}"
    echo -e "${On_Black}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_Red}${MSG1}${Color_Off}"
    echo -e "${On_Red}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_Green}${MSG1}${Color_Off}"
    echo -e "${On_Green}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_Yellow}${MSG1}${Color_Off}"
    echo -e "${On_Yellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_Blue}${MSG1}${Color_Off}"
    echo -e "${On_Blue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_Purple}${MSG1}${Color_Off}"
    echo -e "${On_Purple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_Cyan}${MSG1}${Color_Off}"
    echo -e "${On_Cyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_White}${MSG1}${Color_Off}"
    echo -e "${On_White}${MSG2}${Color_Off}"
    echo -e ""
}
#
function bold_background() {
    print_step "bold_background()"
    echo -e "-- -- -- --"
    echo -e "${On_BBlack}${MSG1}${Color_Off}"
    echo -e "${On_BBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_BRed}${MSG1}${Color_Off}"
    echo -e "${On_BRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_BGreen}${MSG1}${Color_Off}"
    echo -e "${On_BGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_BYellow}${MSG1}${Color_Off}"
    echo -e "${On_BYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_BBlue}${MSG1}${Color_Off}"
    echo -e "${On_BBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_BPurple}${MSG1}${Color_Off}"
    echo -e "${On_BPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_BCyan}${MSG1}${Color_Off}"
    echo -e "${On_BCyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_BWhite}${MSG1}${Color_Off}"
    echo -e "${On_BWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function bold_underline_background() {
    print_step "bold_underline_background()"
    echo -e "-- -- -- --"
    echo -e "${On_UBBlack}${MSG1}${Color_Off}"
    echo -e "${On_UBBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UBRed}${MSG1}${Color_Off}"
    echo -e "${On_UBRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UBGreen}${MSG1}${Color_Off}"
    echo -e "${On_UBGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UBYellow}${MSG1}${Color_Off}"
    echo -e "${On_UBYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UBBlue}${MSG1}${Color_Off}"
    echo -e "${On_UBBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UBPurple}${MSG1}${Color_Off}"
    echo -e "${On_UBPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UBCyan}${MSG1}${Color_Off}"
    echo -e "${On_UBCyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UBWhite}${MSG1}${Color_Off}"
    echo -e "${On_UBWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function high_intensity() {
    print_step "high_intensity()"
    echo -e "-- -- -- --"
    echo -e "${IBlack}${MSG1}${Color_Off}"
    echo -e "${IBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${IRed}${MSG1}${Color_Off}"
    echo -e "${IRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${IGreen}${MSG1}${Color_Off}"
    echo -e "${IGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${IYellow}${MSG1}${Color_Off}"
    echo -e "${IYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${IBlue}${MSG1}${Color_Off}"
    echo -e "${IBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${IPurple}${MSG1}${Color_Off}"
    echo -e "${IPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${ICyan}${MSG1}${Color_Off}"
    echo -e "${ICyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${IWhite}${MSG1}${Color_Off}"
    echo -e "${IWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function bold_high_intensity() {
    print_step "bold_high_intensity()"
    echo -e "-- -- -- --"
    echo -e "${BIBlack}${MSG1}${Color_Off}"
    echo -e "${BIBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BIRed}${MSG1}${Color_Off}"
    echo -e "${BIRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BIGreen}${MSG1}${Color_Off}"
    echo -e "${BIGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BIYellow}${MSG1}${Color_Off}"
    echo -e "${BIYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BIBlue}${MSG1}${Color_Off}"
    echo -e "${BIBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BIPurple}${MSG1}${Color_Off}"
    echo -e "${BIPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BICyan}${MSG1}${Color_Off}"
    echo -e "${BICyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${BIWhite}${MSG1}${Color_Off}"
    echo -e "${BIWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function bold_underline_high_intensity() {
    print_step "bold_underline_high_intensity()"
    echo -e "-- -- -- --"
    echo -e "${UBIBlack}${MSG1}${Color_Off}"
    echo -e "${UBIBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBIRed}${MSG1}${Color_Off}"
    echo -e "${UBIRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBIGreen}${MSG1}${Color_Off}"
    echo -e "${UBIGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBIYellow}${MSG1}${Color_Off}"
    echo -e "${UBIYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBIBlue}${MSG1}${Color_Off}"
    echo -e "${UBIBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBIPurple}${MSG1}${Color_Off}"
    echo -e "${UBIPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBICyan}${MSG1}${Color_Off}"
    echo -e "${UBICyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${UBIWhite}${MSG1}${Color_Off}"
    echo -e "${UBIWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function high_intensity_background() {
    print_step "high_intensity_background()"
    echo -e "-- -- -- --"
    echo -e "${On_IBlack}${MSG1}${Color_Off}"
    echo -e "${On_IBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IRed}${MSG1}${Color_Off}"
    echo -e "${On_IRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IGreen}${MSG1}${Color_Off}"
    echo -e "${On_IGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IYellow}${MSG1}${Color_Off}"
    echo -e "${On_IYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IBlue}${MSG1}${Color_Off}"
    echo -e "${On_IBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IPurple}${MSG1}${Color_Off}"
    echo -e "${On_IPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_ICyan}${MSG1}${Color_Off}"
    echo -e "${On_ICyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IWhite}${MSG1}${Color_Off}"
    echo -e "${On_IWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function bold_high_intensity_background() {
    print_step "bold_high_intensity_background()"
    echo -e "-- -- -- --"
    echo -e "${On_IBBlack}${MSG1}${Color_Off}"
    echo -e "${On_IBBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IBRed}${MSG1}${Color_Off}"
    echo -e "${On_IBRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IBGreen}${MSG1}${Color_Off}"
    echo -e "${On_IBGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IBYellow}${MSG1}${Color_Off}"
    echo -e "${On_IBYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IBBlue}${MSG1}${Color_Off}"
    echo -e "${On_IBBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IBPurple}${MSG1}${Color_Off}"
    echo -e "${On_IBPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IBCyan}${MSG1}${Color_Off}"
    echo -e "${On_IBCyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_IBWhite}${MSG1}${Color_Off}"
    echo -e "${On_IBWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function bold_underline_high_intensity_background() {
    print_step "bold_underline_high_intensity_background()"
    echo -e "-- -- -- --"
    echo -e "${On_UIBBlack}${MSG1}${Color_Off}"
    echo -e "${On_UIBBlack}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UIBRed}${MSG1}${Color_Off}"
    echo -e "${On_UIBRed}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UIBGreen}${MSG1}${Color_Off}"
    echo -e "${On_UIBGreen}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UIBYellow}${MSG1}${Color_Off}"
    echo -e "${On_UIBYellow}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UIBBlue}${MSG1}${Color_Off}"
    echo -e "${On_UIBBlue}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UIBPurple}${MSG1}${Color_Off}"
    echo -e "${On_UIBPurple}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UIBCyan}${MSG1}${Color_Off}"
    echo -e "${On_UIBCyan}${MSG2}${Color_Off}"
    echo -e ""
    echo -e "${On_UIBWhite}${MSG1}${Color_Off}"
    echo -e "${On_UIBWhite}${MSG2}${Color_Off}"
    echo -e ""
}
#
function main() {
    print_step "---- START ----"
    execute_step "init"
    execute_step "regular"
    execute_step "bold"
    execute_step "underline"
    execute_step "bold_underline"
    execute_step "high_intensity"
    execute_step "bold_high_intensity"
    execute_step "bold_underline_high_intensity"
    execute_step "background"
    execute_step "bold_background"
    execute_step "bold_underline_background"
    execute_step "high_intensity_background"
    execute_step "bold_high_intensity_background"
    execute_step "bold_underline_high_intensity_background"
    # execute_step "v3"
    # execute_step "v3"
    # execute_step "v3"
    # execute_step "v4"
}

main "$@"
# main
